### PR TITLE
Add xray docs for policy and watch resources

### PR DESCRIPTION
**Pull request by ryndaniels**
@chb0github here you go

### CODE REVIEW

**Comment by chb0github** [comment]
Can you link to these docs from the main `README.md`?

**Comment by ryndaniels** [comment]
> Can you link to these docs from the main `README.md`?

I could, but I don't see anywhere in `README.md` that links to any of the existing docs. In `docs/index.md` it says `Links to documentation for specific resources can be found in the table of contents to the left.` which makes me think the links should get auto-generated (which seems to be the case for the existing resources). If there's a specific place you'd like me to put links I can do that, but where isn't immediately obvious to me.

**Comment by chb0github** [comment]
Ok, I understand it now - nevermind my request before.

**Review by chb0github — APPROVED** [review]
Looks good

**Pull request merged**
