### PR TITLE
Add new resource artifactory_repository_layout

### LINKED ISSUE #503: Support for Repository Layouts
While the majority of our repositories use the "simple-default" layout we do have a handful of specific repository layouts that we make use of. Currently they're manually configured via the UI, which breaks our goal of having all common Artifactory configurations in config-as-code.

We would be very appreciative if your team could [add support for custom repository layouts](https://www.jfrog.com/confluence/display/JFROG/Repository+Layouts).

### PR DESCRIPTION
**Pull request by alexhung**
Closes #503

### CODE REVIEW

**Review by danielmkn — APPROVED** [review]

**Review by shrajfr12 — APPROVED** [review]
LGTM

**Comment by martinm82** [comment]
@alexhung could it be that there is no documentation available for this feature? I checked https://registry.terraform.io/providers/jfrog/artifactory/6.15.0 and cannot find anything.

**Comment by alexhung** [comment]
@martinm82 You're 100% right! 😞 I'll add that ASAP.

**Comment by alexhung** [comment]
@martinm82 https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/repository_layout

**Pull request merged**
