### PR TITLE
added Force Nuget Authentication option to virtual repo resource

### LINKED ISSUE #44: Add Force Nuget Auth option for virtual Repo also
Hi,

As per the #23 Issue Created a while ago,

It would be great to also have this option when creating a nuget virtual repo. In the Above issue it was only added to Remote and Local.

## New or Affected Resource(s)
```
artifactory_virtual_repository
```
## Potential Terraform Configuration
```
artifactory_virtual_repository {
  force_nuget_authentication = true
}
```

### PR DESCRIPTION
**Pull request by neilbeukes**
Resolves #44

### CODE REVIEW

**Comment by neilbeukes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chb0github** [comment]
So, it's like this: We inherited this repo and the current way it's setup is basically as a "generic +" - Optional params on an otherwise generic repo. 

I will consider this - it's not the ideal approach - ideally, nuget repos would be their own resource encapsulating their own specific details. Ditto for all repos. For example, we have been asked to add a flag to docker remote repos along these same lines. 

Please also sign/accept the CLA

**Comment by chb0github** [comment]
Once you sign the CLA we can merge

**Review by chb0github — APPROVED** [review]
Looks good. Please sign the CLA

**Comment by neilbeukes** [comment]
recheckcla

**Comment by neilbeukes** [comment]
Thanks @chb0github, I did accept the CLA yesterday, seems the bot is bit confused.

**Comment by chb0github** [comment]
Ok. I will look into this.

**Comment by chb0github** [comment]
recheckcla

**Pull request merged**
