### PR TITLE
fix store_artifacts_locally docs to reflect reality

### PR DESCRIPTION
**Pull request by tjstansell**
discovered the docs for `store_artifacts_locally` are incorrect, so this corrects that.

### CODE REVIEW

**Review by alexhung — APPROVED** [review]

**Comment by tjstansell** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck

**Comment by tjstansell** [comment]
recheck

**Comment by alexhung** [comment]
recheck

**Comment by alexhung** [comment]
@tjstansell Not sure why the CLA bot fails. You clearly have signed the CLA 😄 I'll bypass the requirement and merge this.

**Pull request merged**
