### PR TITLE
Fix: remove unwanted line that was part of old config option metadata…

### PR DESCRIPTION
**Pull request by taherbohari**
Fix remote repo document for maven repos

### CODE REVIEW

**Comment by taherbohari** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by taherbohari** [comment]
recheck

**Comment by taherbohari** [comment]
_I have read the CLA Document and I hereby sign the CLA_

**Comment by taherbohari** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Review by alexhung — APPROVED** [review]

**Pull request merged**
