### PR TITLE
Add Artifactory license checking

### PR DESCRIPTION
**Pull request by alexhung**

### CODE REVIEW

**Review by chb0github — APPROVED** [review]

**Comment by jfroche** [comment]
What about `Commercial` type licence ?

**Comment by alexhung** [comment]
@jfroche FYI, I haven't forgotten your question. I'm in the process of confirming the requirement with our product team.

**Comment by jfroche** [comment]
Thank you !

**Comment by alexhung** [comment]
@jfroche I've added a toggle to the provider in #235 which will allow disabling of license checking if desire.

**Pull request merged**
