### PR TITLE
GH-513 Use updated project_key validator

### LINKED ISSUE #513: Project Key - character limitations of 3 to 10 characters
**Describe the bug**
The project key set on a local repository is required to be the project key being the prefix and then the repository key.  It's restricted to 10 characters and most of our repositories are 

projectkey (3 characters) - (repository name 10-15).

```
locals {
  normal_ruby_repositories = {
    img-dssalt-ruby-suo = {
      key = "img-mysalt-ruby-suo"
      project_key = "mykey-img-mysalt-ruby-suo"
    }
  }
}


resource "artifactory_local_gems_repository" "normal_repository" {
  for_each = local.normal_ruby_repositories
  key      = each.value.key
  project_key = each.value.project_key == "" ? null : each.value.project_key
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
1.2.3
- [x] Your version of terraform provider
6.11.0

**Expected behavior**
25 character limit.  

**Additional context**
It may be a simple miss-understanding of how this is meant to work but the same repo via the portal can be added manually, just not via terraform.

### PR DESCRIPTION
**Pull request by alexhung**
Update tests to check for more invalid project_key conditions

Fixes #513

### CODE REVIEW

**Comment by alexhung** [comment]
@apr-1985 ☝🏼 I've created the PR for you 😄

**Comment by apr-1985** [comment]
> @apr-1985 ☝🏼 I've created the PR for you 😄

Thanks so much.  Best Jfrog support I have received :D

**Review by apr-1985 — APPROVED** [review]

**Comment by danielmkn** [comment]
@alexhung, should we add the length constraints to the field description in the documentation? Currently, we have three documents with that field - local.md, virtual.md, and remote.md. 
Usually, we add constraints in the description.

**Comment by alexhung** [comment]
@danielmkn Make sense. Let me add the constraint to the description and docs.

**Pull request closed without merging**
