### PR TITLE
Add gofmt checking

### PR DESCRIPTION
**Pull request by jasonwbarnett**
testing this picks up errors

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
I can't figure this out, but I think it would be nice if this project had a github action that would prevent folks from committing code that isn't properly formatted.

**Comment by chb0github** [comment]
If you do figure it out I would be happy to include it

**Comment by jamestoyer** [comment]
@jasonwbarnett There is also https://github.com/github/super-linter, which can do multiple languages, e.g YAML and Golang. It can target only modified code or all code changed each time. It might be what you're looking for

**Comment by chb0github** [comment]
reopen when ready

**Pull request closed without merging**
