### PR TITLE
Add support for local & remote blockPushingSchema1 option

### LINKED ISSUE #8: Support docker repo setting for blocking manifest v1 publishing
Per https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON, I think this is just a single boolean in a local repo setting for 
```
blockPushingSchema1 = true | false
```

### PR DESCRIPTION
**Pull request by asvoboda**
Resolves #8

### CODE REVIEW

**Comment by asvoboda** [comment]
Depends on https://github.com/atlassian/go-artifactory/pull/27 being merged first, unfortunately.

**Comment by asvoboda** [comment]
Hey @DarthFennec, I see that in ba711e0cd240689cc9e9b33d1e0288a6a41d8e9a you introduced a new backing client which already supports this property. Should I just wait for the migration to the backing client, or is this PR okay as is? Is the atlassian/go-artifactory client even maintained at this point?

**Comment by peters95** [comment]
Hi @asvoboda the atlassian client go is now deprecated we are switching this provider to use the jfrog go cli client.

**Comment by asvoboda** [comment]
It sounds like I'll want to wait for that migration to happen first then? Do you guys have a milestone or set of issues I can follow along for the migration? :)

**Comment by peters95** [comment]
@asvoboda We are actively working on this transition now. @chb0github is the developer who is taking over this effort.

**Pull request closed without merging**
